version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo npm install -global sfdx-cli
      - run:
          name: SFDX version
          command: |
              sfdx --version
              sfdx plugins --core
      - run:
          name: Create Scratch Org
          command: |
            mkdir keys
            echo $SFDC_SERVER_KEY | base64 -d > keys/server.key
            echo "Authenticating..."
            sfdx force:auth:jwt:grant --clientid $SFDC_PROD_CLIENTID --jwtkeyfile keys/server.key --username $SFDC_PROD_USER --setdefaultdevhubusername -a DevHub
            echo "Creating the Scratch Org..."
            sfdx force:org:create -f config/project-scratch-def.json -a ${CIRCLE_BRANCH} -s

      - run:
            name: Delete Scratch
            command: |
              sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p