version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo npm install -global sfdx-cli
      - run:
          name: SFDX version
          command: |
              sfdx --version
              sfdx plugins --core
      - run:
          name: Create Scratch Org
          command: |
            mkdir keys
            echo "Generate Key"
            openssl enc -nosalt -aes-256-cbc -in config/server.key -out server.key.enc -base64 -K $SFDC_SERVER_KEY -iv $SFDC_SERVER_IV
            echo "Authenticating..."
            sfdx force:auth:jwt:grant --clientid $SFDC_CONSUMER_KEY \
                                      --jwtkeyfile config/server.key \
                                      --username $SFDC_USER \
                                      --setdefaultdevhubusername -a DevHub \
                                      --instanceurl https://login.salesforce.com
            echo "Creating the Scratch Org..."
            sfdx force:org:create -f config/project-scratch-def.json -a circle_build_$CIRCLE_BUILD_NUM -s
            sfdx force:org:create --definitionfile config/project-scratch-def.json \
                                  --targetdevhubusername DevHubTiime \
                                  --setalias circle_build_$CIRCLE_BUILD_NUM \
                                  --wait $DEPLOY_TIMEOUT
            sfdx force:org:open --targetusername circle_build_$CIRCLE_BUILD_NUM \
                                --urlonly
      - run:
            name: Delete Scratch
            command: |
              sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p