public without sharing class BATCH_WS04/* implements Queueable, Database.AllowsCallouts */{
    
    /*public void execute(QueueableContext context) {
    	try {
	    	WS04_Companeo ws = new WS04_Companeo();
	    	ws.getAllNewLeadsFromCompaneo();
	    	
	    	if(!Test.isRunningTest()) {
	    		System.enqueueJob(new BATCH_WS04());
	    	}
    	} catch(Exception e) {
    		Utils.createLogError(e);
    	}
    }*/
}